name: Android Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Project
        run: |
          chmod +x ./gradlew 
          ./gradlew clean assemble

      - name: Run Tests
        run: ./gradlew test

      - name: Static Analysis
        run: ./gradlew ktlintCheck detekt