name: Danger Checks

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6


      - name: Perform Git operation
        run: git fetch --depth=100

      - name: Update RubyGems
        run: gem update --system 3.2.3

      - name: Danger Checks
        run: |
          gem install bundler
          bundle install
          bundle exec danger

        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}