name: Danger Checks

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: '2.6'

      - name: Danger Checks
        run: |
          gem install bundler
          bundle install
          bundle exec danger

        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}